name: Deploy Web

on:
  push:
    branches: [adachi/develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.WEB_VERCEL_DEPLOY_HOOK_URL }}"
